### ISSUE TITLE
F-14A Helios Driver

### ISSUE THREAD

**Issue by MedievalBunny** [HeliosVirtualCockpit/Helios#787] opened 2024-01-05 07:09 UTC
Hopped into a campaign with the F-14A tonight and discovered Helios not working as well as I expected. Helios to DCS communication is fine, all switches and buttons work as expected, but DCS to Helios communication seemed to be totally broke, no switch positions or lights updated from DCS.

Diving into the problem I found the F-14 Interface and export scripts all correctly included the F-14A vehicle name, but there was no driver created in Saved Games\DCS\Scripts\Helios\Drivers\. Making a copy of the F-14B driver, renaming it, and changing the name at the top of the file seems to have gotten everything working just fine. 

Is this expected behavior? I didn't see any indication in the Profile Editor that files were out of date and both the Interface Status and DCS F-14B tabs indicated everything was set up. Or is this just a quirk of one Interface trying to handle multiple DCS vehicles?

**Comment by BlueFinBima** [comment] 2024-01-05 10:11
@MedievalBunny Hi Alex,  I think what you're talking about is "Vehicle Impersonation" which was not fully implemented in 1.6.  Getting this working for SoftInterfaces is what I am working on at the moment, and hoping to deliver in 1.6.6060.  I bought the Tomcat module, but never had the time to learn how to fly it (and I don't have a profile using the dedicated interface).  The important piece of Vehicle Impersonation is that the driver has all of the capability to deal with all of the variants.  Sounds like you might have sorted that out in your latest PR.   Would you be up for testing the new Vehicle Impersonation against the Tomcat (when it is ready).

**Comment by MedievalBunny** [comment] 2024-01-05 20:53
@BlueFinBima Yah, I'd be happy to test out new features!

**Comment by BlueFinBima** [comment] 2024-01-22 09:03
@MedievalBunny There is a release candidate build of 1.6.606 [here](https://github.com/HeliosVirtualCockpit/Helios/actions/runs/7603929749/artifacts/1184263325).  I think you should have access to it.  This should allow both Tomcat variants to be used, but you will need to perform a "Setup DCS" on the F-14B interface in Profile Editor (ideally the interface name should have changed, but this causes all sorts of problems).  Please let me know if you hit any snags.

**Comment by MedievalBunny** [comment] 2024-01-22 19:36
Hi @BlueFinBima - the link is throwing a 404 error for me.

Once I get it, should I delete my renamed copy of the F-14B driver that I created before installing?

**Comment by BlueFinBima** [comment] 2024-01-22 20:30
@MedievalBunny You got to this before I could update the link.  I needed to make a change, and I deleted the installer.  The new one is [here](https://github.com/HeliosVirtualCockpit/Helios/actions/runs/7616703314/artifacts/1186799167)

**Comment by BlueFinBima** [comment] 2024-01-23 10:30
Duplicate of #765

**Comment by BlueFinBima** [comment] 2024-01-24 22:55
@MedievalBunny Many thanks for the testing and feedback.  You'll need to manually uninstall the 1.6.6060.1 before installing the released version.

**Closed by BlueFinBima** 2024-01-24 22:55 UTC
Labels: duplicate, enhancement
