### ISSUE TITLE
Put a dark background for F-15E MPDs like gauges faceplate

### ISSUE THREAD

**Issue by rocketeer998** [HeliosVirtualCockpit/Helios#818] opened 2024-03-30 04:26 UTC
I've reported before that the 3 F-15E MPD appear to be transparent in VR mode. But you guys just said it is a DCS problem.

These are put in viewport category. All gauges in the non viewport category have faceplates. Then needles are animated over these dark faceplate making them readable. Can the same be done to the MPDs by having a dark background?

Currently there is a fill monitor background checkbox, and and a 'use background' checkbox for each MPD. Both don't do anything to prevent the MPDs appearing transparent in VR mode. All gauges have dark background due to their faceplates. All MPDs don't and are thus unreadable.
![F-15E in VR](https://github.com/HeliosVirtualCockpit/Helios/assets/145094080/46537cca-51c9-4053-87ac-31ff6970077e)
![Capture](https://github.com/HeliosVirtualCockpit/Helios/assets/145094080/839d7453-fb9e-4754-9bf3-4d3152eeb5fc)
![Capture2](https://github.com/HeliosVirtualCockpit/Helios/assets/145094080/ae979a5a-0b54-4435-8aec-264ca7fe7515)

**Comment by BlueFinBima** [comment] 2024-04-01 20:51
Hi @rocketeer998 Nothing that you've reported here changes the answer that this is a DCS Module issue.  Helios can't alter whether a viewport is exported by DCS with a background or not.  I understand that the fact that there is a background checkbox on the viewport is "anomalys", however to remove this checkbox, I'd have to make changes to core HeliosVisual which is used by pretty much every control in Helios, and it would not actually help you,  so I choose to leave it the way it is.
I'm closing this as a duplicate of #756.

**Closed by BlueFinBima** 2024-04-01 20:51 UTC
Labels: duplicate
