### ISSUE TITLE
Helios Profil AH-64D

### ISSUE THREAD

**Issue by Michael3478** [HeliosVirtualCockpit/Helios#783] opened 2023-12-28 20:18 UTC
Hi

I'm currently in the process of creating a Helios profile for Apache. It's almost finished so far.

Now I'm still missing the HAT switches, but unfortunately I can't get them to work. Can someone please help me with this? 4 way switch I can't get the bindings???

Which bindings should be set for the 4-way switch?

New interface bindings?

I hope it can help me. Of course I would be happy to make the profile available to Helios users. PLT and CPG work without any problems and I have already completed almost all the switches I need. The viewports, Tedac, KU and displays also fit perfectly and it's fun to fly with a functioning profile. Whether single or Multi, switching between the seats is no longer a problem, as the key files are now assigned to the occupied seat without having to switch in the control settings.

Thanks to Bluefina and Helios for your work here...

greeting

Michael

**Comment by BlueFinBima** [comment] 2023-12-28 22:28
Hi Michael,  I've transferred your issue to a more appropriate repository, and the correct Organisation.  There is a Wiki for Helios which has a section about [getting help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help), and your question is probably best asked in Capt Zeen's discord channel since this has the most active grouping of Helios users.
I have not tried to implement a HAT switch myself, however I do recall putting the CPG hat switches into the AH-64D interface, and I was recently reading code from a different profile which mapped a hat's  X-Y directions onto discrete positions on a single hidden rotary switch ( I think this was in Captain Zeen's F-16C interface).

If there are missing interface functions, then these can be added to the Helios AH-64D JSON interface, or you can list their Arg ID's m in this issue and I can look into adding them.

Hope this helps to some degree.

**Comment by Michael3478** [comment] 2023-12-29 08:24
Hello
Many thanks for the quick response. I'll take care of it now and provide a solution to the problem as soon as I have the answer. Unfortunately I couldn't upload any pictures here in my post otherwise it might have been clearer what it was about. The functions have been implemented, but they do not yet work properly.
Thank you again for your quick response.

greeting
Michael

**Comment by Michael3478** [comment] 2023-12-31 08:11
Hi

I've probably found the "mistake". In the bindings, the interface assignment is somehow not correct. That's what I believe. The bindings of the interface have the following assignment:

Trigger Value
Numeric:
1 = Up, 2 = Middle, 3 = Down

Ation Value
Numeric
Position 0 = center, 1=Up, 2 =down, 3 = left, or 4 =right

Trigger value should then look like this::
1 = Up, 0 = center, 3 = Down

The bindings do not fit on all four way switches.

I've posted the "problem" in various forums, but haven't received an answer. Sorry for raising my problem here again, but maybe you have a solution for me.
![Man TRK](https://github.com/HeliosVirtualCockpit/Helios/assets/155083349/cac8d4f5-d4c2-4c55-b553-cd649ba38323)
![Binding](https://github.com/HeliosVirtualCockpit/Helios/assets/155083349/b38cf6bd-47d2-4bcf-94af-2c6b73334dd9)

greeting
Michael

**Comment by BlueFinBima** [comment] 2024-01-03 12:01
I'll investigate when I get some free time.  Please let me know if you make progress yourself.

**Comment by MedievalBunny** [comment] 2024-01-05 21:44
I've always struggled with Four-Way Hats too. I've found that's it's easiest to create each direction as a separate button in the Interface, and then bind them to the individual hat directions. That's not a simple solution though.

Another option, I think, would be for the Interface to build the entire hat as a 5-possition switch, rather than two 3-possition switches. I've not tried that though.

**Comment by MedievalBunny** [comment] 2024-01-06 06:00
Update: making a 5-possition switch didn't work, so I still think just making everything single buttons works best.

Unless there's a way to make this work with the "Value Source" drop-down? I've never seen any documentation on how that feature works. Or maybe there's something else I'm missing entirely.

**Comment by BlueFinBima** [comment] 2024-01-06 10:31
Hi Alex, I think the 5 position switch can be made to work - at least from
observation -  this is what CZ does in at least one of his profiles (F-16
maybe).  It might require a new synthetic argument in the exports and
interface change to accept it.  I have this on the list of things to
investigate, but probably not in the short term.

**Comment by MedievalBunny** [comment] 2024-01-06 22:44
I gave it a try on the F-16, since I had a profile already built and ready to use for testing. 
Building a new 5-way switch in the Interface and trying it out, the result was a mess. and it kept confusing the left/right and up/down movement directions. I suspect the cause is that DCS uses a different id for the horizontal and vertical components of the switch, and I'm not aware of a way to build a single switch with multiple ids.

**Comment by BlueFinBima** [comment] 2024-01-07 14:59
Alex, you're correct that a switch with multiple args is not possible, but
CZ combined the horizontal arg and the vertical arg into a single arg
before sending to (in his case) the generic interface.  When I have a few
moments free, I'll try to cobble something together.

**Comment by Michael3478** [comment] 2024-01-09 12:02
Hi
I've tried everything in the past few days, but unfortunately without success. The problem with the windshield wiper is that the switch only recognizes 3 positions.
The parking position cannot be used because the switch only recognizes 3 positions.
I then solved this using a key. In the DCS key file, a key combination is assigned to the Park, Off, Lo and Hi functions and then set in the profile editor using “send key”. You then have to repeat the assigned command to change the parking position, which then looks like this:
{LCONTROL}jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj

The other positions OFF, Lo and HI require one key.
Off= {LCONTROL}l
LO = {LCONTROL}k
HI = {LCONTROL}h

I think that when recalling the parking position it needs a momentary switch while the other positions Off, Lo and HI need a toggle. Thank you very much at this point that I am not working on this alone and I am sure that there is a solution for every problem.

Greetings
Michael

**Comment by MedievalBunny** [comment] 2024-01-09 19:20
In the F-16, my solution so far as been to create 4 buttons out of the two 3-possition switches, then bind each direction of the 4-way switch to a button press and release. The code to turn a single 3-way switch into two buttons in the Interface looks like this:

![interface code](https://github.com/HeliosVirtualCockpit/Helios/assets/19675397/079e38e6-b6e8-40bf-99ad-6c79b5adab4c)

Which when bound in Helios then looks like this:

![helios binds](https://github.com/HeliosVirtualCockpit/Helios/assets/19675397/27b05443-62dc-49e3-bdd7-28c8c82cfb3e)

Repeat the exact same thing for the other direction, so you have 4 buttons total, each with a press and release function.

The windshield wiper switch in the Apache is a rotary switch, so that should work just fine in Helios already. If you have an Input bind the switch in Helios will follow the one in the DCS cockpit. The Park function is not supposed to always stay in place in the Apache, it's only available when certain conditions are met. I don't remember the exact conditions, but it springing back out of Park to Off is an Apache feature, not a Helios bug.

**Comment by BlueFinBima** [comment] 2024-01-23 17:32
Current plan is to add capability to the existing hat switch control to allow it to function from separate horizontal and vertical inputs.  Hopefully this will help reduce the complexity of this.
I'm testing this at the moment.

**Comment by BlueFinBima** [comment] 2024-01-29 07:51
Shipped in 1.6.606

**Closed by BlueFinBima** 2024-01-29 07:51 UTC
Labels: enhancement, Delivered

**Comment by Michael3478** [comment] 2024-01-29 14:52
Hello

Thanks for your quick help. New Helios is installed and runs without any problems. The switch is inserted and all functions are perfect.
Now I can finish my profile and make it available to the community.
Great job sir.

Greetings
Michael
