### ISSUE TITLE
Resolution is coming up with incorrect values

### ISSUE THREAD

**Issue by brlowe1965** [HeliosVirtualCockpit/Helios#420] opened 2021-05-17 22:46 UTC
[Helios has written the report to the file 'Helios_status_report_132657651327936832.txt' and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]

**Comment by derammo** [comment] 2021-05-17 23:02
[InterfaceStatusIssue420.txt](https://github.com/HeliosVirtualCockpit/Helios/files/6497334/InterfaceStatusIssue420.txt)

**Comment by derammo** [comment] 2021-05-22 23:40
reproduced below.   Note this is as designed, since the assumption is that DCS would position the main window to the top of the desktop (not the top of the monitors column that is used.)      This requires testing to see if DCS will actually position the window as Helios assumes or at the top of the main display.  Also, it could matter whether the top is the main display or another display.   The design would then have to be changed.

![image](https://user-images.githubusercontent.com/817160/119243528-89883d00-bb35-11eb-86ad-7de6a231c322.png)

**Comment by brlowe1965** [comment] 2021-05-23 17:32
When I did it like this on my system the resolution came out much taller which would have been ok but when I started DCS I did not have a resolution option for it and I ended up with only the top half of DCS showing so I could not apply any changes as the buttons were on the bottom half that you could not see. The top half of the DCS screen was just black. I got it to work but lining monitors 1 and 2 even at the top. Then my resolution was a selectable option and it works great so far.

**Comment by derammo** [comment] 2021-05-23 19:16
@brlowe1965 thanks that matches what I am thinking.  It seems like DCS is actually sliding the main window to the top of the monitor column and not to the top of the desktop, as the code assumes.  To really test this, I need to set up a test machine with about 5 monitors so I can try various combinations again.  I also don't know if it was always wrong or if DCS has changed since I first tested this, because the case of "there is an unused monitor to the left that also sticks up" wasn't one of my test cases I think (?) 

What a nightmare.  For the record, I had two requests for actual answers about the placement algorithm in to Eagle and they apparently got as far as the dev team but they didn't return anything useful.

**Comment by hivet01090** [comment] 2021-07-17 07:14
Hello,
i have same problem.
My solution: 
-turn off all Helios programs.
-turn on "DCS"
-save our actual setup "register1"
-open "DCS", in options check "full sreen", and put the right resolution of your main monitor. Click "save"
Dcs will restart.
-then make your "register1" on
-"DCS" restart.
Turn on helios profiler en reset monitor for your profil.
That all.
For me work fine. 
Put DCS full screen make it at the good place on your main monitor when it's not in full screen(multiple monitor setup)
So i would llike to apologies for my english language. i am better in french.

**Comment by derammo** [comment] 2021-07-22 21:32
I am working on trying to fix this situation.  However, right now it appears to me this ONLY makes a mistake when you set "Fullscreen" in DCS Options.   Then it will position the window incorrectly or squish things.

If Fullscreen is not, set, then it always works correctly.   Can you please show me a case where it fails with Fullscreen off?
@brlowe1965 @hivet01090

**Comment by hivet01090** [comment] 2021-07-23 13:01
yes it's true. 
i've made an initial installation of DCS. Then i install helios and put in Helios Profoile Editor my helios's profile. 
And the problem revelead. I intent a lot of manipulations in helios profile editor, but the only way was to change the condition of display in DCS: first :full screen, second: windowed.
After that, all was right. So i think there is no problem in helios, only in DCS who make wrong display

**Comment by derammo** [comment] 2021-07-23 13:15
I will leave this bug open until @brlowe1965 has a chance to chime in.

**Comment by brlowe1965** [comment] 2021-07-23 13:24
I have changed my monitors around in the last 2 months and reconfigured both my computers so I really cannot duplicate the issue again. DCS and Helios have been working and I have not had any of the config issues again.  My main DCS computer has 4 monitors, 55" 4K, 15.6" HD touch and 2 7" MFD screens and all is working the way it should. Sorry I cannot try to duplicate it at this time.

**Comment by derammo** [comment] 2021-07-23 13:26
It's ok I don't want more bugs to work on :).   Closing this as no repro.

#421 now tells people if they are in Fullscreen and that stuff might not work

**Comment by derammo** [comment] 2021-07-23 13:27
And thank you for responding.

**Comment by brlowe1965** [comment] 2021-07-23 13:27
Thanks for working on a great product.

**Closed by derammo** 2021-07-23 13:26 UTC
Labels: More Info Needed
