### ISSUE TITLE
[regression] Text Display scaling broken between 1.4.2020.0530 and 1.6.3045.0001

### ISSUE THREAD

**Issue by BlueFinBima** [HeliosVirtualCockpit/Helios#273] opened 2020-07-07 12:25 UTC
Simple test using the hornet UFC and the hornet interface, scaled in PE using shift drag to keep aspect ratio.  In 1.4, the text is scaled but in 1.6.3045.0001 it is not.   Test case is "00000000:2096=~0 ".  I have not investigated to see how widespread the issue is.
I believe that this is the problem @derammo mentioned in #213 however derammo's problem was different from the problem reported by the creator of the issue.
Before investigating further, I'd be interested if anyone has a suggestions for commits which might have introduced this issue.

**Comment by BlueFinBima** [comment] 2020-07-07 12:50
I'm going to assume that the implementation of the new autoscaling options probably have a part to play in this.  If I assume that the new scaling of the TextDisplay is more correct, I am unclear why we need a legacy 1.4 option.  The scaling is not contained in the profile so therefore there should be no need to do it the "incorrect" way for people using PE now.  They just get the scaling (or no scaling) that we give them 1.6 and probably have no way to tell that it is different.  Am I missing something?

Back to the initial issue above, I guess this scaling problem is linked to textdisplays within more complext visual components.

**Comment by derammo** [comment] 2020-07-07 12:52
obviously I messed this up when I changed Text Display scaling to introduce the new "accurate" scaling mode.  

There is really no need to investigate, as this is clearly reproducible according to what you said above.  Not sure what the string means you gave as a Test Case.  But if all that I have to do is scale the UFC, that's easy.  If you really want to work on it, be my guest, but I am most familiar with the code since I was the one who broke it :).  

So assign it to me unless you are already fixing it.  I just don't want to do anything if you are already doing it.  

If you are doing it, check if the default scaling mode of "Legacy" is not being used by text displays in composite controls.  If it was somehow defaulting to "none" then that would explain the lack of scaling.

**Comment by derammo** [comment] 2020-07-07 12:54
you are missing something :)

the legacy mode is supposed to be the default for existing profiles, so they continue to scale as before. That's why it is the default if nothing is set in the profile.  Newly created controls default to the accurate mode, so any new profiles will have that set.  At least that's how it is supposed to work.

**Comment by BlueFinBima** [comment] 2020-07-07 13:19
> you are missing something :)
> 



> the legacy mode is supposed to be the default for existing profiles, so they continue to scale as before. That's why it is the default if nothing is set in the profile. Newly created controls default to the accurate mode, so any new profiles will have that set. At least that's how it is supposed to work.

**Comment by BlueFinBima** [comment] 2020-07-07 13:26
The testcase is simply the command to send to get the 20  character to appear in the Comm2 of the UFC.

**Comment by derammo** [comment] 2020-07-08 01:58
There are profiles out there that resize just barely correctly to where people can still read the text through the cockpit masks.  I am not touching that.  If people want it to scale the new way, they can switch their controls over to the new mode.

**Comment by derammo** [comment] 2020-07-08 02:28
I was supposed to get a packed "20" for ~0?   I get this:  

![image](https://user-images.githubusercontent.com/817160/86867644-31715500-c0a1-11ea-9310-3ab9b4bd3611.png)

**Comment by derammo** [comment] 2020-07-08 02:29
unrelated to the problem, but just checking if you meant char 20 or the number 20 in 16 elements

**Comment by derammo** [comment] 2020-07-08 02:36
ok here is what I get scaling down by around 50%

1.6
![image](https://user-images.githubusercontent.com/817160/86868164-371b6a80-c0a2-11ea-9669-057e598cc4b8.png)

1.4
![image](https://user-images.githubusercontent.com/817160/86868096-13582480-c0a2-11ea-83b7-f2eacf3d6a47.png)

so ok that confirms that it's broken.  It is scaling, just wrong.   So I will go fix that.

**Comment by derammo** [comment] 2020-07-08 03:38
ok all better now.  I did not notice the CompositeVisual code was programmatically replacing the TextFormat object in the TextDisplay object, so the new mode was not working.  And it also was not using legacy mode, because that only gets switched on for TextEdit controls created from profile XML.  The TextDisplay objects in the CompositeVisual don't show up in the XML, so they are created in code every time.  

What I ended up doing is just adapting CompositeVisual to the new code and letting it use the new "Height" mode.  This required changing TextEdit to not fail when the TextFormat object is replaced.  An alternative could have been to disallow replacing that object and just making CompositeVisual configure the one that is already there.  

There doesn't appear to be any similar code anywhere else in the code base.

**Comment by BlueFinBima** [comment] 2020-07-08 17:19
@derammo, thanks for the quick work.  All fields verified with
``00000000:2094=123.456:2092=~:2093=~:2095=`8:2096=~0:2091=!:2090=!:2089=!:2088=!:2087=!:2086=~~~~:2085=~~~~:2084=~~~~:2083=~~~~:2082=~~~~: 
``
![image](https://user-images.githubusercontent.com/18526232/86949568-c4b09600-c146-11ea-96e4-5b6650bd6748.png)

**Closed** 2020-07-08 17:26 UTC
Labels: Verified, bug, fixed
