### ISSUE TITLE
Incomplete Number Conversion in F/A-18 UFC

### ISSUE THREAD

**Issue by icemarkom** [HeliosVirtualCockpit/Helios#605] opened 2022-08-27 02:58 UTC
**To Reproduce**

In F/A-18, on either one of the "MFD"s (use left or bottom, because process in the plane takes over right at one point):

- Select HSI
- Choose waypoint using up or down arrows
- Press DATA (top-right)
- Select PRECISE (bottom)
- Press UFC (top-left)
- Press GRID on the UFC
- On the right MFCD, select a two letter grid using TDC
- On the UFC, enter a long (10-digit) grid coordinate.

Some digit combinations (i.e. 78, 89) will need to be converted to a single-character glyph, similar to how `~0` is converted to a single-glyph representing number 20. In-game UFC handles this, and Helios one does not.

Specifically, I believe the following list of conversions is incomplete: https://github.com/HeliosVirtualCockpit/Helios/blob/master/Helios/Gauges/FA-18C/UFC/UFC.cs#L33

Related to the above, conversion for `12` involves a non-printable ASCII 173 character (per https://github.com/BlueFinBima/DCS-Fonts/blob/master/FA-18C%20and%20AV-8B%20UFC/Output/Hornet%20UFC%20%20Mapping.PDF; which is also incomplete :-) ), and that is not possible (?) to enter using profile editor to manually override this behavior.

**Expected behavior**

All numbers in the Helios UFC are correctly displayed.

**Screenshots**
- Repro-steps video (using F/A-18 Free Flight): https://youtu.be/Ar35QtD8FfM
- Screenshots attached.

**please complete the following information:**
 - Helios Version: 1.6.5306.4
 - DCS Version: 2.7.17.29140 Open Beta
 - [x] Profile Editor
 - [ ] Control Center
 - [ ] Keypress Receiver
 - [x] Something else (*remember to tell us what it is*): Helios F/A-18 UFC
![PXL_20220827_023000797](https://user-images.githubusercontent.com/10375507/187011582-5bc4c0c5-168e-4d6d-90e2-97bf1498a80b.jpg)
![PXL_20220827_023008901](https://user-images.githubusercontent.com/10375507/187011586-139c6438-0344-49c6-b6ae-75b007c4dc87.jpg)
![PXL_20220827_023024007](https://user-images.githubusercontent.com/10375507/187011590-71ad48a7-1dd9-489b-a453-5ed52f2e0f0d.jpg)

**Comment by BlueFinBima** [comment] 2022-08-27 07:20
Interesting, I'll take a look when I get some free time.  This character is a new one on me
![image](https://user-images.githubusercontent.com/18526232/187019661-11ca0812-5fdb-4add-ba6a-874810c6f558.png)
and I don't think it was in the Hornet character set when I built this.  
@icemarkom can yo tell me whether your UFC was scaled from the original 1920x1080.  Helios doesn't always get the scaling right, and this might be the cause of the ellipsis.

**Comment by icemarkom** [comment] 2022-08-27 07:46
This is not the scaling issue - conversion simply doesn't happen for these combinations of digits in Helios' UFC. There is also `12` missing for radio channels 1 and 2. Note though, that ellipsis is not the issue. It's the `M` :-)

**Comment by BlueFinBima** [comment] 2022-08-27 08:10
Ellipsis is an issue, but possibly not a concern to you.  I'll take a look
when I get some time

**Comment by icemarkom** [comment] 2022-08-28 00:05
Of course - sorry for sounding insensitive about it not being an issue. I just thing it's a different one, as I've observed, but not researched an usual behavior that is probably more related to the font than UFC. I.e., I think that one photo shows two different issues.

Once *I* find a bit more time, I can file a separate issue regarding the font scaling for this particular font.

**Comment by BlueFinBima** [comment] 2022-08-29 09:31
The "12" problem isn't that the code is missing (although it is undeniably missing) , but the reason it is missing is because it is a soft hyphen and does not have a character code.  The real issue is that  Extended ascii 173 should never have been used in the first place. I'll find another character to replace it.
Your proposed designs for the double digits in the 16 segment displays both have their issues.  You're right that creating a character code for all double digits is not sensible, but trying to cram two digits into one 16 segment display has it's challenges.  The ellipsis is a symptom of the same problem, and is caused by two characters attempting to fit into a single character position (and not caused by scaling).
It'll take me some time to relearn how to use the font editor, and also to find the latest source code for that particular font.  I also need to do some testing to determine the most pragmatic way to display double digits >19.

**Comment by icemarkom** [comment] 2022-08-29 15:04
Re: 12

I did mention that in the original report. An unfortunate choice of a control character, indeed. It could be worked around in the code by using ASCII code directly, but it makes extended implementation within GUI difficult/not possible without modifying the input field to support the same.

There is no solution without its own problems to any non-trivial engineering problem is my answer for the rest :-).

**Comment by BlueFinBima** [comment] 2022-08-29 16:31
I tried using the character code 173, and it didn't work.  Anyway, that bit is fixed now.  I have a design for the other problem, but now just need to make it work.

**Comment by BlueFinBima** [comment] 2022-08-29 17:34
Looks like the design has promise
![image](https://user-images.githubusercontent.com/18526232/187263026-89d79c89-675c-4075-85a2-e9fc559fcc4e.png)

**Comment by BlueFinBima** [comment] 2022-08-30 20:39
A few bumps in the road with this due to the way that DCS handles the tens digit for the display which meant that the dictionary had to be a lot more involved than I initially thought.  The fix for this issue is not backwardly compatible, however the UFC remains autobinding, so this should not be a big problem.  Just delete the UFC in profile editor and re-add it.  This should be resolved by https://github.com/HeliosVirtualCockpit/Helios/commit/7eb31b816b9ff152c9c1fff2763afc602bb1d436

**Comment by icemarkom** [comment] 2022-08-30 20:57
Great stuff - thanks for fixing it!

Now... it would be great if the dictionary you used could somehow be used for other input fields. Allow me to explain, while fully understanding this is NOT the same issue, and is more of a feature request.

See... I don't actually like using the faux-texture UFC or other gauges. I've rebuilt my own set of controls to suit my needs. And the only reason I ended up filing this bug is that I was scratching my head trying to figure out what is going on, and then debugged my gauges using the UFC shipped with Helios. 

Is there any way we can somehow "expose" these conversion dictionaries to the folks trying to do the similar as I am. If anything, that silly "12" is a problem :-)

**Comment by BlueFinBima** [comment] 2022-08-31 08:56
I "fixed" the scratchpad problem using two dictionaries (left side and right side), and in reality, this has fixed the 12 problem twice in different ways.  The last two segments of the scratchpad are the only elements which use both dictionaries.  The right side dictionary is the original one with the "12" fixed so for 99.99% of the cases, this is good enough.
I've put a template into Helios for the ODU which exposes the right side dictionary.  This is not autobinding.
I've also put a template in for the whole UFC scratchpad which does not expose the dictionaries (but you've already shown that you know where they live in the code) and does allow turning off the background so provides some flexibility (and working for the precision use-case).

I have to confess to being amazed by the UFC using two numbers in a single 16 segment display because there are so many combinations which appear identical, but I guess you see the correct values as they scroll before getting messed up in the last position.

**Comment by BlueFinBima** [comment] 2022-08-31 09:09
The above enhancement has been made in 661a52a087a44df20ce76b8f4c66a87229057602

**Comment by BlueFinBima** [comment] 2022-09-05 08:24
Shipped in [1.6.5307.9](https://github.com/HeliosVirtualCockpit/Helios/releases/latest)

**Closed by BlueFinBima** 2022-09-05 08:24 UTC
Labels: bug, fixed
