### ISSUE TITLE
new Layers Panel icons take focus away from editor

### ISSUE THREAD

**Issue by linknetx** [HeliosVirtualCockpit/Helios#387] opened 2020-12-28 07:47 UTC
Helios version 1.6.3424.0000

Selecting a layer in the layers panel and pressing the delete key randomly fails to delete the layer. After restarting Helios the delete key works again. It seems to fail after using one of the new "lock all" and "unlock all" selection buttons at the top of the layers panel.

**Comment by derammo** [comment] 2020-12-29 15:50
when this happens, is the selection rectangle in the visual editor view grey (as opposed to blue) like this?

![image](https://user-images.githubusercontent.com/817160/103296158-82646500-49c3-11eb-93e1-3bc7b65d7bf2.png)

if so, that just means that the focus is not on that window.   This should probably be fixed but does not indicate a code error I think.

**Comment by linknetx** [comment] 2020-12-29 16:00
Ah, in the previous version selecting an item in the layers panel must have set focus on the particular window, now in this latest version that doesn't happen.

**Comment by derammo** [comment] 2020-12-29 16:02
it is SUPPOSED to... but the binding between selecting something in the layers and focus ending up on the visual editor is very indirect (the original code really likes handling collection change events instead of just calling functions ;)) 

so yeah it is possible there are some paths now where the focus is lost.  It is not acting the way I would prefer.   But if that's all it is, then it isn't gonna blow up on us

**Comment by linknetx** [comment] 2020-12-29 16:10
Looking into it a bit further, if i open the editor and manually unlock items then clicking in the layers panel always sets focus.

However after using Unlock All even only once then focus is never set whether an item is manually unlocked or globally unlocked throughout the whole profile until Helios is restarted.

Unlock and Unlock All are making some global change in Helios until it is restarted.

**Comment by derammo** [comment] 2020-12-29 16:17
ok great.  having a reproducible test case like that greatly increases the chance I will fix it :)

**Comment by derammo** [comment] 2020-12-29 18:40
blue selection indicates the keyboard focus is on that editor, which is why the delete key works

the icons bar in the layers panel needs to not take keyboard focus when used, because Helios relies on the keyboard focus remaining on the visual editor

**Comment by derammo** [comment] 2020-12-29 18:50
released as 3425

**Closed** 2020-12-29 18:52 UTC
Labels: bug, fixed
