### ISSUE TITLE
Formatting issue with UFC and F-18 Font

### ISSUE THREAD

**Issue by damien022** [HeliosVirtualCockpit/Helios#346] opened 2020-09-14 14:49 UTC
When using the Helios F-18 UFC, the character representing the "Active" selection for the 5 screens on the right is showing a 0 or a 1, rather than blank and :

Space characters on the top left screen are shown as _

![image](https://user-images.githubusercontent.com/4340320/93101110-ca27e080-f6a1-11ea-9c72-fb4bb6e364a0.png)

**Comment by derammo** [comment] 2020-09-14 15:00
either a bad merge when I recently integrated BFB's work on that or maybe the encoding is actually changed in DCS.   Recommend testing with 1.4 first to rule out DCS actually changed it.

**Comment by BlueFinBima** [comment] 2020-09-14 16:29
DCS handling appears unchanged for UFC_OptionCueingx.  This looks like 2087-2091 have been changed to a boolean somewhere.  As for the spaces, again the handling by DCS seems to be unchanged.

**Comment by derammo** [comment] 2020-09-14 17:45
when you say unchanged, does that mean you tested it with 1.4 and 1.4 works correctly with the current latest DCS OpenBeta?

just asking because that's the first thing I would check otherwise :)

**Comment by derammo** [comment] 2020-09-14 17:45
oh I just saw your comment about you can't test.  never mind :)

**Comment by BlueFinBima** [comment] 2020-09-14 20:41
I meant that the results from parse_indication(6) at 2.5.6.54046 are nothing peculiar.  
It is almost as if UFC_OptionCueingx  are going through  helios.textureToString rather than helios.ensureString, but none of the code I looked at had a change like this.

**Comment by BlueFinBima** [comment] 2020-09-26 07:31
https://forums.eagle.ru/showpost.php?p=4500814&postcount=225 also reporting the IFEI nozzle indicators not working.

**Comment by Denver29** [comment] 2020-09-26 09:05
Hello

I confirm I have the same problem with UFC option cueing with 1 and 0 instead of : and blank.
I also encounter problems with the UEFI nozzle needle that doesn't move

**Comment by Denver29** [comment] 2020-09-26 09:11
And i also notice a problem with the HUD symbology in the main DCS view that became very wide and almost unreadable whereas DDI and AMPCD viewport in helios profile are very thin but quite readable.

**Comment by BlueFinBima** [comment] 2020-09-26 10:38
@Denver29 HUD symbology is definitely unrelated to the previous problems you describe.  Happy for you to open a new issue and include screenshots to demonstrate the problem.

**Comment by BlueFinBima** [comment] 2020-09-26 10:41
UFC cueing bug is caused by the optional "format" argument of helios.send which is not equating to nil when not specified.

**Comment by derammo** [comment] 2020-09-26 11:37
@BlueFinBima I added the optional argument to support some existing ExportFunctions.lua.    I did not anticipate that there were calls out there that were erroneously sending extra arguments.  Sorry about that.

@BlueFinBima could you explain or comment why the cueing is changed from character 200 to the exclamation point in the second file?

**Comment by derammo** [comment] 2020-09-26 11:51
also: during any review that I did, I would not have noticed that gsub returns two arguments which are then sent on.   ugh.  nice debugging!

**Comment by BlueFinBima** [comment] 2020-09-26 13:13
It was not easy to debug.  I hate debugging Lua.  I did briefly consider also checking for "%" in the formatting string because of the subtlety of this problem.

The value of 200 still works, but harks back to the days when I was mapping character codes in the exports.  The code to map "!" to the 200 is already implemented in the textdisplay dictionary for the field, so that mapping change was just cosmetic.  If I recall, this was another improvement you guilted me into doing.

**Comment by derammo** [comment] 2020-09-26 15:46
I won't use optional arguments in Lua again.  This is really unsafe stuff.  There is nothing in the code that would tell you that two arguments are being filled from two return values of the previous call.  If I had been aware this was a thing in Lua, I would have just ported the ExportFunctions code instead of making an optional argument to keep the old code working.

**Comment by BlueFinBima** [comment] 2020-09-27 15:39
Missed Damien's comment about spaces "Space characters on the top left screen are shown as _" which is generated by `helios.send(2094, string.format("%7s", helios.ensureString(li.UFC_ScratchPadNumberDisplay)))`
I have not seen this problem myself, but it will not be fixed by the option cueing fix.  Hmmm....

**Comment by BlueFinBima** [comment] 2020-09-27 15:48
@damien022 I was not able to reproduce the underscore problem in the scratchpad.  Any thoughts?
![image](https://user-images.githubusercontent.com/18526232/94369373-43cbbf80-00e1-11eb-9fb1-01f961f9641c.png)

**Comment by BlueFinBima** [comment] 2020-09-27 15:50
BTW @Denver29 & @damien022 please let me know if you want the fix for the option cueing and IFEI nozzle needles and I'll make it available.

**Comment by Denver29** [comment] 2020-09-28 22:34
If it's not too much work for you sure i would love to hace that problem fix!!
Thanks

**Comment by BlueFinBima** [comment] 2020-10-20 08:08
@damien022 please open a new issue if you continue to see the underscore problem
![image](https://user-images.githubusercontent.com/18526232/96557999-f5aa7600-12b2-11eb-9911-b7aee5280ea5.png)
Closing this issue because the cueing problem has been fixed.

**Closed by BlueFinBima** 2020-10-20 08:08 UTC
Labels: bug, fixed
