### ISSUE TITLE
Helios not scaling to monitor size when "Reset Monitors"

### ISSUE THREAD

**Issue by MadKreator37** [HeliosVirtualCockpit/Helios#847] opened 2024-11-12 05:52 UTC
# HELP US TO HELP YOU

If you are having problems installing / configuring / using a profile then you should use the support process for the provider of that profile.

- [ x] I have read [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)
---
### Describe the Helios Issue
- Installing profile created in different resolution than own monitor causes wild scaling issues. 

- Currently in question,  is a profile created/ modified  in 1280x720 and resetting monitors to 1920x1080

### Steps to Reproduce the problem
Steps to reproduce the behaviour:
1. Install profile as normal
2. reset monitors, set "scale to monitor size" ( same effect when "scale to fit content" used), select proper monitors, click ok

### Expected behavior
- Profile will be fitted to appropriate screen size

### Screenshots
![Screenshot 2024-11-11 224034](https://github.com/user-attachments/assets/8e7f7864-51c8-4d90-bd94-4f3e26f74ac2)
![Screenshot 2024-11-11 224235](https://github.com/user-attachments/assets/f8dfc189-82f2-4016-995f-88f256f0593b)

### Please complete the following information:
 - Helios Version 1.6.611.5

### The problem happened while using 
(place an 'x' between the square brackets for all that apply)
 - [x ] Profile Editor
 - [ ] Control Center
 - [ ] Keypress Receiver
 - [ ] Something else (*remember to tell us what it is*)

### Additional context
Same result whether scaling up or down between monitor sizes

**Comment by BlueFinBima** [comment] 2024-12-02 09:34
likely to be the same root cause as #845

**Comment by MadKreator37** [comment] 2024-12-02 17:19
I was thinking it would be linked in some way.

**Comment by BlueFinBima** [comment] 2024-12-07 13:05
@linknetx tests suggest that this worked fine at 1.6.610.

**Comment by BlueFinBima** [comment] 2024-12-08 16:51
HotFix 1 should address this problem.  It is available [here](https://github.com/HeliosVirtualCockpit/Helios/releases/tag/1.6.6111.1)

**Comment by linknetx** [comment] 2024-12-08 19:15
> HotFix 1 should address this problem. It is available [here](https://github.com/HeliosVirtualCockpit/Helios/releases/tag/1.6.6111.1)

Yes, that works perfectly. Thanks.

**Comment by MadKreator37** [comment] 2024-12-08 21:32
Awesome! Thanks so much!

**Comment by BlueFinBima** [comment] 2024-12-23 10:24
Fixed in shipped release  1.6.6120,2

**Closed by BlueFinBima** 2024-12-23 10:24 UTC
Labels: bug, fixed
