### ISSUE TITLE
Patches not installing in 2.8 helios 1.6.5400.0002

### ISSUE THREAD

**Issue by MadKreator37** [HeliosVirtualCockpit/Helios#636] opened 2022-11-01 20:21 UTC
[Helios_status_report_133118076160594880.txt](https://github.com/HeliosVirtualCockpit/Helios/files/9913727/Helios_status_report_133118076160594880.txt)

**Comment by MadKreator37** [comment] 2022-11-01 20:35
just found discord chat with this issue.. disabled only the ka-50 patches and all others install fine

**Comment by BlueFinBima** [comment] 2022-11-02 21:42
Another duplicate of #630

**Closed by BlueFinBima** 2022-11-02 21:42 UTC
Labels: duplicate
