### ISSUE TITLE
Add Interface: Unhandled error in Helios

### ISSUE THREAD

**Issue by PopTopsBarty** [HeliosVirtualCockpit/Helios#485] opened 2021-11-06 10:47 UTC
Helios is working like a charm on my computer. I wanted to add an interface allowing me to bind a "joystick" controller input so I can use my hardware instead of a touchscreen. Unfortunately when clicking the "+" sign on the top of the screen I'm receiving an error message from Helios; Unhandled error in Helios (screenshot included).
After clicking away the error message I receive an empty interface window
![Unhandled error](https://user-images.githubusercontent.com/93821789/140606819-81c1a267-bbf2-43d8-9bb4-e7d59cf214dc.PNG)
![Unhandled error empty Interface window](https://user-images.githubusercontent.com/93821789/140606835-641c7bb9-be5f-47d1-984f-80bf99c54086.PNG)
[Profile Editor Problems.log](https://github.com/HeliosVirtualCockpit/Helios/files/7490269/Profile.Editor.Problems.log)

I already performed a reinstall on a different drive but no luck so far

**Comment by Todd1215** [comment] 2021-11-06 11:40
My first suggestion is to uninstall Helios then go and make sure the entire directory is removed so that there are no old files hanging around. Once that is done reinstall and retest.

**Comment by PopTopsBarty** [comment] 2021-11-06 12:31
Hi, thx, I did that already and unfortunately it didn’t work out…

**Comment by Todd1215** [comment] 2021-11-08 16:01
Just curious, how many USB devices do you have attached to your PC?

**Comment by PopTopsBarty** [comment] 2021-11-08 16:17
That must be about 15 I believe

**Comment by Todd1215** [comment] 2021-11-09 16:23
I assume since you are a cockpit builder that possibly you might have several homegrown / DIY devices? I know this is asking allot but have you tried adding an interface with all USB devices unplugged?

**Comment by Todd1215** [comment] 2022-01-09 13:32
Based on comment's in issue #491 it seems that some DIY controllers can cause Helios to crash.

**Comment by ereidelbach** [comment] 2022-01-11 14:03
Apologies for the delay in getting back to you @Todd1215, I unexpectedly had to travel for a family emergency but I'm back now.

That said, I see you closed this and #491 already, but I owe you some more troubleshooting time this weekend. I disconnected both of my DIY controllers (with possible duplicated HID IDs) but that did not immediately resolve the problem at the time.

I'm going to unplug everything this weekend and systematically add them back one at a time to see if I can resolve/reproduce the error just to confirm the suspected source of the error. 

Thanks for staying on top of these issues!

**Comment by ereidelbach** [comment] 2022-01-17 19:08
Can confirm that I no longer have this bug after removing both DIY controllers (zero delay encoders) that shared the same HID ID.

After removing aformentioned devices, I have been able to "add interfaces" to new profiles without any issues.

Thanks again for your time.

**Comment by MedievalBunny** [comment] 2022-01-28 04:41
I also have the exact same problem. 

I've only got a single DIY USB controller, also running on a Zero Delay board. Unplugging it allowed me to install an Interface fine.

**Comment by Todd1215** [comment] 2022-11-02 13:20
whelp, it seems you have the same issue. With that said I believe we need some error handling code to not crash when it finds two devices with the same HID ID.

**Comment by BlueFinBima** [comment] 2022-12-23 07:57
@MedievalBunny do you still have the option to reproduce the problem you were seeing?

**Closed** 2022-12-23 14:21 UTC
Labels: bug, More Info Needed
