### ISSUE TITLE
Control Center crashes on startup

### ISSUE THREAD

**Issue by DH14300** [HeliosVirtualCockpit/Helios#365] opened 2020-10-16 01:21 UTC
I have version 1.6.3308.0 which is new. Profile editor seems to work fine but when I launch Control Center it crashes immediately. I took a snapshot of the error message and search for ControlCenter and ProfileEditor logs but could not find any. Any help would be much appreciated.
Thank you.
Dan H.
Littleton CO USA

<img width="321" alt="CrashError" src="https://user-images.githubusercontent.com/72954284/96202104-8b44af00-0f1b-11eb-8b3f-990fe09ec10a.png">

[debug.log](https://github.com/HeliosVirtualCockpit/Helios/files/5388662/debug.log)

**Comment by BlueFinBima** [comment] 2020-10-16 06:40
@DH14300 Hi Dan,  helios.ico should be laid down in   _installation directory_\Helios Virtual Cockpit\Helios\Graphics\ did you move the Helios program files to another location?  Does Helios.ico exist in the about directory?

**Comment by DH14300** [comment] 2020-10-16 12:04
I uninstalled this morning so I will reinstall latest version and check to make sure it is there and report back to you. Thank you for your response!
Dan

**Comment by DH14300** [comment] 2020-10-16 12:34
OK... I reinstalled the latest version to the default directory (as before) and the Helios.ico is there - C:\Program Files\Helios Virtual Cockpit\Helios\Graphics\Helios.ico. Same problem. Here's the message...
<img width="315" alt="Crash10-16-20" src="https://user-images.githubusercontent.com/72954284/96258706-a47c4880-0f79-11eb-9cd5-b0e6eb417b04.png">

**Comment by BlueFinBima** [comment] 2020-10-16 19:53
Hi Dan,  What release of Windows are you running?

**Comment by derammo** [comment] 2020-10-16 22:35
I was just going to ask that too.  

1) What version of Windows is this? 
2) Are you running something like high contrast accessibility mode?
3) Did you turn off all UI effects or something like that?
4) Did any previous version of Helios work for you?  Which one?

**Comment by BlueFinBima** [comment] 2020-10-17 07:39
@derammo Aero warning panel?

**Comment by BlueFinBima** [comment] 2020-10-17 08:10
I can reproduce this with Win 7 and MSTSC.  I believe that we have said in the past that 1.6 would not support Windows 7 so it will be interesting to hear what the operating system environment is.

**Comment by BlueFinBima** [comment] 2020-10-17 09:06
Likely circumvention is to add this into ControlCenterPreferences.xml (back it up first!) inside HeliosSettings->Group->ControlCenter->Settings 
```
<?xml version="1.0" encoding="utf-8"?>
<HeliosSettings>
  <Group>
    <Name>Preferences</Name>
    <Settings />
  </Group>
  <Group>
    <Name>ControlCenter</Name>
    <Settings>
      <Setting>
        <Name>WindowLocation</Name>
        <Value>200,200,704,476</Value>
      </Setting>
```
**Add this next block**
```
      <Setting>
        <Name>AeroWarning</Name>
        <Value>False</Value>
      </Setting>
```

```
    </Settings>
  </Group>
</HeliosSettings>
```

**Comment by derammo** [comment] 2020-10-17 17:51
probable fix by BlueFinBima (eee76c762f9f474322de2098508b8193b9c8dd9e) in build https://github.com/HeliosVirtualCockpit/Helios/releases/tag/1.6.3309.0

**Comment by DH14300** [comment] 2020-10-18 02:17
Hello,

Thank you for looking into this. I'm running Windows 7 64 bit.

 
 

Sent: Friday, October 16, 2020 at 1:53 PM

**Comment by DH14300** [comment] 2020-10-18 02:21
Hello,

 

1. I'm running Windows 7 Home 64 bit

2. I'm not sure what high contrast accessibilty mode is. Is this an operating system setting?

2. 'UI' effects? Again, not sure what that is. My apologies!

4. This is my 1st attempt to use Helios.

 

Thank you for looking into this. I appreciate it! I would really love to use Heilos with my flight simulator setup! I am using 3 & sometime 4 monitors.

 

Dan

 
 

Sent: Friday, October 16, 2020 at 4:35 PM

**Comment by DH14300** [comment] 2020-10-18 02:22
Thank you and I will definitely give it a try!

 

Dan

 
 

Sent: Saturday, October 17, 2020 at 11:51 AM

**Comment by DH14300** [comment] 2020-10-18 02:23
I will definitely add the code below and see what happens!

Thank you.

 

Dan

 
 

Sent: Saturday, October 17, 2020 at 3:06 AM

**Comment by BlueFinBima** [comment] 2020-10-18 06:25
@DH14300 Hi Dan, thanks for the confirmation.  What derammo was asking was whether the Windows 7 Aero desktop was being used and the fact that you saw this failure probably means that you are not using Aero.  There is a fix for this problem in the next release of Helios.  I hope you enjoy the virtual cockpit experience with Helios.

**Closed by BlueFinBima** 2020-10-18 06:25 UTC
Labels: Verified, bug, fixed

**Comment by DH14300** [comment] 2020-10-18 19:50
Hello again,

I attempted to add the edit you specitified in the file 'ControlCenterPreferences.xml' below. While Helios is installed on my 'C' drive, I searched for the file 'ControlCenterPreferences.xml' and no such file was found. Could this be the cause of my error?

 

I did find 'HeliosSettings.xml' located in C:\Users\Dan\My Documents\Helios.

 

Thank you and appreciate your guidance trying to troubleshoot this issue!

 

Sincerely,

Dan

 
 

Sent: Saturday, October 17, 2020 at 3:06 AM

**Comment by BlueFinBima** [comment] 2020-10-18 20:53
@DH14300 Hi Dan,  m y guess is that you don't have a ControlCenterPreferences.xml because you have not successfully run Control Center.  I suggest you try https://github.com/HeliosVirtualCockpit/Helios/releases/download/1.6.3309.0/Helios_Installers.zip because this should fix the problem. I'd also suggest upgrading Windows.  Cheers

**Comment by DH14300** [comment] 2020-10-19 01:33
That worked! I installed 1.6.3309.0 and Control Center opens fine It has let me know I'm missing some DCS World patches which I'm installing now (7+ Gig update!). Thank you for your help. Will you be supporting monitors with different resolutions? My cockpit has 3 small displays and 1 large view for the external view as shown.
Thanks!
Dan
![20200725_165905](https://user-images.githubusercontent.com/72954284/96392254-c263cc00-1178-11eb-97e5-6ca44fb953f6.jpg)

**Comment by derammo** [comment] 2020-10-19 13:03
Hi Dan.   I can see you are new to open source software and GitHub.   Please don't post on this closed issue.  You are notifying all the developers and sending emails to a bunch of people.  Don't punish us for having fixed this bug by sending us a bunch more mails :).

This issue is closed.  If you encounter another bug, please create another issue/ticket.

For help resources, please read through this page:  https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help
