### ISSUE TITLE
CHANGE THIS TITLE TO SOMETHING MEANINGFUL

### ISSUE THREAD

**Issue by Leonski73** [HeliosVirtualCockpit/Helios#781] opened 2023-12-19 21:24 UTC
# HELP US TO HELP YOU
## Change the title text to something relevant and follow the instructions below.

If you are having problems installing / configuring / using a profile then you should use the support process for the provider of that profile.

- [ ] I have read [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)
---
## *[Helios has written the report to the file* `Helios_status_report_133474947599094449.txt` *and opened its containing folder in Explorer.  Please drag and drop it from Explorer to here and replace this message with a description of the problem you are reporting.]*

---
### Describe the Helios Issue
*A clear and concise description of what the bug is, when it started to happen and any recent changes.*

### Steps to Reproduce the problem
Steps to reproduce the behaviour:
1. *Go to '...'*
2. *Click on '....'*
3. *Scroll down to '....'*
4. *See error*

### Expected behavior
*A clear and concise description of what you expected to happen.*

### Screenshots
*If applicable, add screenshots to help explain your problem.*

### Please complete the following information:
 - Helios Version [eg *1.6.6040.3*]
 - DCS Version [e.g. *Open Beta 2.7.16.28111*]
 - BMS Version

### The problem happened while using 
(place an 'x' between the square brackets for all that apply)
 - [ ] Profile Editor
 - [ ] Control Center
 - [ ] Keypress Receiver
 - [ ] Something else (*remember to tell us what it is*)

### Additional context
*Add any other context about the problem here.  (eg this problem started happening when I ....)*

**Comment by Leonski73** [comment] 2023-12-19 21:24
TEDAC.init.Lua

dofile(LockOn_Options.common_script_path.."devices_defs.lua")
dofile(LockOn_Options.script_path.."Displays/MFD/device/MFD_device_IDs.lua")
dofile(LockOn_Options.script_path.."Displays/MFD/indicator/MFD_Tools.lua")
dofile(LockOn_Options.script_path.."Displays/MFD/indicator/MFD_Opacity_Materials.lua")

opacity_sensitive_materials = 
{
	"font_TEDAC",
	"font_TEDAC_BLACK",
	"font_TEDAC_big",
	"font_TEDAC_big_BLACK",
	"TEDAC_SYMBOLOGY",
	"TEDAC_SYMBOLOGY_BLACK",
	"font_TEDAC_FCR_Target_symbol",
	"font_TEDAC_FCR_Target_symbol_black",
	"TEDAC_FCR_INDICATION_WHITE",
	"TEDAC_FCR_INDICATION_BLACK",
}

color_sensitive_materials = 
{
	"font_TEDAC",
	"font_TEDAC_big",
	"TEDAC_SYMBOLOGY",
	"TEDAC_FCR_INDICATION_WHITE",
	"TEDAC_FCR_INDICATION_BLACK",
}

brightness_sensitive_materials = 
{
	"font_TEDAC",
	"font_TEDAC_big",
	"TEDAC_SYMBOLOGY",
	"TEDAC_FCR_INDICATION_WHITE",
	"TEDAC_FCR_INDICATION_BLACK",
}


addOpacitySensitiveMaterials(opacity_sensitive_materials, "TEDAC")
addOpacitySensitiveMaterials(color_sensitive_materials, "TEDAC")

local ResourcesPath = LockOn_Options.script_path.."../IndicationResources/"
local IndicationTexturesPath = ResourcesPath.."Displays/TEDAC/"

used_render_mask_day	= IndicationTexturesPath.."TEDAC_day.dds"
used_render_mask_night	= IndicationTexturesPath.."TEDAC_night.dds"

-- Parameters handling functions
indicator_type	= indicator_types.COMMON
purposes		= {render_purpose.BAKE}--{render_purpose.GENERAL}

dofile(LockOn_Options.script_path.."Displays/TEDAC/TEDAC_PagesInit.lua")

--
use_parser					= false
dynamically_update_geometry	= false

writeParameter("MFD_NUM", MFD_SELF_IDS.TEDAC)
writeParameter("FONT_PREFIX", "font_TEDACMFD_")

**Comment by BlueFinBima** [comment] 2023-12-19 21:47
Duplicate of #778

**Closed by BlueFinBima** 2023-12-19 21:47 UTC
Labels: duplicate
