### ISSUE TITLE
Indicator Controls Now Randomly Saving Font Size since 1.6.5400.2

### ISSUE THREAD

**Issue by linknetx** [HeliosVirtualCockpit/Helios#642] opened 2022-11-10 18:15 UTC
When opening a profile saved with a previous version of Helios which contains existing Caution Indicator, Annunciator or Indicator-Square Controls the font scaling option defaults to "Use the legacy code from Helios 1.4". This means that the font size now appears as a random value in the control and on saving the profile it is saved as this random value. Reopening the profile and resaving results in another random font size value. This problem has only existed since the Helios 1.6.5400.2 update.

Also when adding these controls to a profile when using Helios 1.6.5400.2 the default font scaling option is not identical between them. The Caution Indicator defaults to "Adjust font size based on height of control" whereas the Annunciator and Indicator-Square default to "Use the legacy code from Helios 1.4".

**To replicate the problem using Helios 1.6.5400.2:**

1. Add a Caution Indicator to a blank profile and set the scaling mode to "Use the legacy code from Helios 1.4" then change the size of the control so that it is different to the default size. Save the profile. Restart the PE and open this profile and save under a different name. Compare the two profile files using a file comparison program and the font size will have changed.

2, Repeat this but set the scaling mode to "Adjust font size based on height of control" and the same problem occurs.

**Comment by BlueFinBima** [comment] 2022-11-11 10:09
@linknetx is this a duplicate of #637 ?  If so, I have a fix already committed for this.

**Comment by linknetx** [comment] 2022-11-11 10:39
@BlueFinBima Just built the latest and it does fix the font sizes changing on profile load but it doesn't address the second part:

When adding these controls to a profile when using Helios 1.6.5400.2 the default font scaling option is not identical between them. The Caution Indicator defaults to "Adjust font size based on height of control" whereas the Annunciator and Indicator-Square default to "Use the legacy code from Helios 1.4".

**Comment by BlueFinBima** [comment] 2022-11-11 11:40
@linknetx Good spot.  My thinking is that new controls being added should move over to font scaling by height.  What do you think?

**Comment by linknetx** [comment] 2022-11-11 12:18
@BlueFinBima Definitely, so that the Annunciator and Indicator-Square would change to "Adjust font size based on height of control" by default.

**Comment by BlueFinBima** [comment] 2022-11-11 12:32
OK, if you don't mind, I'll add a commit for this to #637 rather than spreading the changes over multiple issues.

**Comment by BlueFinBima** [comment] 2022-11-11 12:54
@linknetx Looks like it is just 4 templates which need to be tweaked so no code as such.

**Comment by linknetx** [comment] 2022-11-11 12:58
> OK, if you don't mind, I'll add a commit for this to #637 rather than spreading the changes over multiple issues.

That's fine with me,

**Comment by BlueFinBima** [comment] 2022-11-11 14:14
fix to second point added in PR #643.

**Closed by BlueFinBima** 2022-11-11 14:14 UTC
